### ISSUE TITLE
Language server does not work with default template

### ISSUE THREAD

**Issue by VictorLandim** [rescript-lang/rescript-vscode#238]
Hello there. I'm facing issues while opening the default [project template](https://github.com/rescript-lang/rescript-project-template) on vscode. The language server just crashes.

Vscode version: 1.56.0
Extension: v1.1.1
OS: Windows 10 with WSL2
Node: v14.15.5
NPM: 7.6.1

.compiler.log
```
#Start(1620743667710)
#Done(1620743667710)
```

This is some of the data from the output tab:

```
/home/victor/.vscode-server/extensions/chenglou92.rescript-vscode-1.1.1/server/analysis_binaries/linux/rescript-editor-analysis.exe: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/victor/.vscode-server/extensions/chenglou92.rescript-vscode-1.1.1/server/analysis_binaries/linux/rescript-editor-analysis.exe)
/home/victor/.vscode-server/extensions/chenglou92.rescript-vscode-1.1.1/server/analysis_binaries/linux/rescript-editor-analysis.exe: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/victor/.vscode-server/extensions/chenglou92.rescript-vscode-1.1.1/server/analysis_binaries/linux/rescript-editor-analysis.exe)
child_process.js:637
    throw err;
    ^

Error: Command failed: /home/victor/.vscode-server/extensions/chenglou92.rescript-vscode-1.1.1/server/analysis_binaries/linux/rescript-editor-analysis.exe hover /home/victor/dev/rescript/demo/src/Demo.res 0 3
/home/victor/.vscode-server/extensions/chenglou92.rescript-vscode-1.1.1/server/analysis_binaries/linux/rescript-editor-analysis.exe: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/victor/.vscode-server/extensions/chenglou92.rescript-vscode-1.1.1/server/analysis_binaries/linux/rescript-editor-analysis.exe)
/home/victor/.vscode-server/extensions/chenglou92.rescript-vscode-1.1.1/server/analysis_binaries/linux/rescript-editor-analysis.exe: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/victor/.vscode-server/extensions/chenglou92.rescript-vscode-1.1.1/server/analysis_binaries/linux/rescript-editor-analysis.exe)

    at checkExecSyncError (child_process.js:616:11)
    at Object.execFileSync (child_process.js:634:15)
    at Object.runAnalysisAfterSanityCheck (/home/victor/.vscode-server/extensions/chenglou92.rescript-vscode-1.1.1/server/out/utils.js:147:31)
    at process.onMessage (/home/victor/.vscode-server/extensions/chenglou92.rescript-vscode-1.1.1/server/out/server.js:338:32)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(686) [Uint8Array] [
       47, 104, 111, 109, 101,  47, 118, 105,  99, 116, 111, 114,
       47,  46, 118, 115,  99, 111, 100, 101,  45, 115, 101, 114,
      118, 101, 114,  47, 101, 120, 116, 101, 110, 115, 105, 111,
      110, 115,  47,  99, 104, 101, 110, 103, 108, 111, 117,  57,
       50,  46, 114, 101, 115,  99, 114, 105, 112, 116,  45, 118,
      115,  99, 111, 100, 101,  45,  49,  46,  49,  46,  49,  47,
      115, 101, 114, 118, 101, 114,  47,  97, 110,  97, 108, 121,
      115, 105, 115,  95,  98, 105, 110,  97, 114, 105, 101, 115,
       47, 108, 105, 110,
      ... 586 more items
    ]
  ],
  pid: 23943,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(686) [Uint8Array] [
     47, 104, 111, 109, 101,  47, 118, 105,  99, 116, 111, 114,
     47,  46, 118, 115,  99, 111, 100, 101,  45, 115, 101, 114,
    118, 101, 114,  47, 101, 120, 116, 101, 110, 115, 105, 111,
    110, 115,  47,  99, 104, 101, 110, 103, 108, 111, 117,  57,
     50,  46, 114, 101, 115,  99, 114, 105, 112, 116,  45, 118,
    115,  99, 111, 100, 101,  45,  49,  46,  49,  46,  49,  47,
    115, 101, 114, 118, 101, 114,  47,  97, 110,  97, 108, 121,
    115, 105, 115,  95,  98, 105, 110,  97, 114, 105, 101, 115,
     47, 108, 105, 110,
    ... 586 more items
  ]
}
[Info  - 3:37:56 PM] Connection to server got closed. Server will restart.
[Error - 3:37:56 PM] Request textDocument/hover failed.
Error: Connection got disposed.
```

**Comment by cristianoc** [comment]
Looks like it's trying to run the linux executable for some reason.

**Comment by VictorLandim** [comment]
> Looks like it's trying to run the linux executable for some reason.

Shouldn't it? I'm using the windows's 10 linux subsystem.

**Comment by cristianoc** [comment]
Great so it will work on the next release.

**Comment by cristianoc** [comment]
@VictorLandim the new release is out.
