### ISSUE TITLE
EISDIR error happening

### ISSUE THREAD

**Issue by LukasDeco** [rescript-lang/rescript-vscode#356]
Hello!

I am seeing a crash in the output of the Rescript Language Server:

(node:1452) UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, watch '//wsl$/Ubuntu/home/luksd/Repos/occasionally-for-business/realm-app/hosting/lib/bs/.compiler.log'
    at FSWatcher.<computed> (internal/fs/watchers.js:218:26)
    at Object.watch (fs.js:1525:34)
    at createFsWatchInstance (c:\Users\Owner\.vscode\extensions\chenglou92.rescript-vscode-1.2.1\server\node_modules\chokidar\lib\nodefs-handler.js:119:15)
    at setFsWatchListener (c:\Users\Owner\.vscode\extensions\chenglou92.rescript-vscode-1.2.1\server\node_modules\chokidar\lib\nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (c:\Users\Owner\.vscode\extensions\chenglou92.rescript-vscode-1.2.1\server\node_modules\chokidar\lib\nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (c:\Users\Owner\.vscode\extensions\chenglou92.rescript-vscode-1.2.1\server\node_modules\chokidar\lib\nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (c:\Users\Owner\.vscode\extensions\chenglou92.rescript-vscode-1.2.1\server\node_modules\chokidar\lib\nodefs-handler.js:629:21)
    at async c:\Users\Owner\.vscode\extensions\chenglou92.rescript-vscode-1.2.1\server\node_modules\chokidar\index.js:445:21
    at async Promise.all (index 0)
(Use `Code --trace-warnings ...` to show where the warning was created)
(node:1452) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1452) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Has this been seen before by anyone? I know this file exists so I'm not sure why it is thinking it's a directory... but I am also not very familiar with this node error.

I'm on Windows 10 running WSL 2 Ubuntu inside it. Extension was working fine before when I ran it directly on windows.

**Comment by LukasDeco** [comment]
I was able to solve this issue once I installed the Remote Development extension pack from Microsoft, opened my repo from inside the Ubuntu connection, and installed the extension from inside wsl. This error will happen to you if you are editing a repo inside WSL but the extension is installed in your normal windows.
