### ISSUE TITLE
Extension crashes because rescript-editor-analysis.exe cannot handle `semanticTokens` or `codeAction` query

### ISSUE THREAD

**Issue by jayesh-bhoot** [rescript-lang/rescript-vscode#488]
When I open a .res file in VS Code, the extension crashes because rescript-editor-analysis.exe cannot handle `semanticTokens` or `codeAction` query.

Error log:

```
node:child_process:887
    throw err;
    ^

Error: Command failed: /nix/store/s3c7g5x3bgjl28nwjy9wdrzisqnbykf1-vscode-extension-chenglou92-rescript-vscode-1.3.0/share/vscode/extensions/chenglou92.rescript-vscode/server/analysis_binaries/linux/rescript-editor-analysis.exe semanticTokens /tmp/rescript_format_file_68739_0.res

**Private CLI For rescript-vscode usage only**

API examples:
  ./rescript-editor-analysis.exe completion src/MyFile.res 0 4 currentContent.res
  ./rescript-editor-analysis.exe definition src/MyFile.res 9 3
  ./rescript-editor-analysis.exe typeDefinition src/MyFile.res 9 3
  ./rescript-editor-analysis.exe documentSymbol src/Foo.res
  ./rescript-editor-analysis.exe hover src/MyFile.res 10 2
  ./rescript-editor-analysis.exe references src/MyFile.res 10 2
  ./rescript-editor-analysis.exe rename src/MyFile.res 10 2 foo

Dev-time examples:
  ./rescript-editor-analysis.exe dump src/MyFile.res src/MyFile2.res
  ./rescript-editor-analysis.exe test src/MyFile.res

Note: positions are zero-indexed (start at 0 0), following LSP.
https://microsoft.github.io/language-server-protocol/specification#position

Options:
  completion: compute autocomplete for MyFile.res at line 0 and column 4,
    where MyFile.res is being edited and the editor content is in file current.res.

    ./rescript-editor-analysis.exe completion src/MyFile.res 0 4 current.res

  definition: get definition for item in MyFile.res at line 10 column 2:

    ./rescript-editor-analysis.exe definition src/MyFile.res 10 2

  typeDefinition: get type definition for item in MyFile.res at line 10 column 2:

    ./rescript-editor-analysis.exe typeDefinition src/MyFile.res 10 2

  documentSymbol: get all symbols declared in MyFile.res

    ./rescript-editor-analysis.exe documentSymbol src/MyFile.res

  hover: get inferred type for MyFile.res at line 10 column 2:

    ./rescript-editor-analysis.exe hover src/MyFile.res 10 2

  references: get all references to item in MyFile.res at line 10 column 2:

    ./rescript-editor-analysis.exe references src/MyFile.res 10 2

  rename: rename all appearances of item in MyFile.res at line 10 column 2 with foo:

    ./rescript-editor-analysis.exe rename src/MyFile.res 10 2 foo

  dump: for debugging, show all definitions and hovers for MyFile.res and MyFile.res:

    ./rescript-editor-analysis.exe dump src/Foo.res src/MyFile.res

  test: run tests specified by special comments in file src/MyFile.res

    ./rescript-editor-analysis.exe test src/src/MyFile.res


    at checkExecSyncError (node:child_process:846:11)
    at Object.execFileSync (node:child_process:884:15)
    at Object.func (node:electron/js2c/asar_bundle:5:1812)
    at Object.runAnalysisAfterSanityCheck (/nix/store/s3c7g5x3bgjl28nwjy9wdrzisqnbykf1-vscode-extension-chenglou92-rescript-vscode-1.3.0/share/vscode/extensions/chenglou92.rescript-vscode/server/out/utils.js:172:31)
    at Object.runAnalysisCommand (/nix/store/s3c7g5x3bgjl28nwjy9wdrzisqnbykf1-vscode-extension-chenglou92-rescript-vscode-1.3.0/share/vscode/extensions/chenglou92.rescript-vscode/server/out/utils.js:177:26)
    at semanticTokens (/nix/store/s3c7g5x3bgjl28nwjy9wdrzisqnbykf1-vscode-extension-chenglou92-rescript-vscode-1.3.0/share/vscode/extensions/chenglou92.rescript-vscode/server/out/server.js:375:26)
    at process.onMessage (/nix/store/s3c7g5x3bgjl28nwjy9wdrzisqnbykf1-vscode-extension-chenglou92-rescript-vscode-1.3.0/share/vscode/extensions/chenglou92.rescript-vscode/server/out/server.js:790:18)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(2181) [Uint8Array] [
       10,  42,  42,  80, 114, 105, 118,  97, 116, 101,  32,  67,
       76,  73,  32,  70, 111, 114,  32, 114, 101, 115,  99, 114,
      105, 112, 116,  45, 118, 115,  99, 111, 100, 101,  32, 117,
      115,  97, 103, 101,  32, 111, 110, 108, 121,  42,  42,  10,
       10,  65,  80,  73,  32, 101, 120,  97, 109, 112, 108, 101,
      115,  58,  10,  32,  32,  46,  47, 114, 101, 115,  99, 114,
      105, 112, 116,  45, 101, 100, 105, 116, 111, 114,  45,  97,
      110,  97, 108, 121, 115, 105, 115,  46, 101, 120, 101,  32,
       99, 111, 109, 112,
      ... 2081 more items
    ]
  ],
  pid: 68804,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(2181) [Uint8Array] [
     10,  42,  42,  80, 114, 105, 118,  97, 116, 101,  32,  67,
     76,  73,  32,  70, 111, 114,  32, 114, 101, 115,  99, 114,
    105, 112, 116,  45, 118, 115,  99, 111, 100, 101,  32, 117,
    115,  97, 103, 101,  32, 111, 110, 108, 121,  42,  42,  10,
     10,  65,  80,  73,  32, 101, 120,  97, 109, 112, 108, 101,
    115,  58,  10,  32,  32,  46,  47, 114, 101, 115,  99, 114,
    105, 112, 116,  45, 101, 100, 105, 116, 111, 114,  45,  97,
    110,  97, 108, 121, 115, 105, 115,  46, 101, 120, 101,  32,
     99, 111, 109, 112,
    ... 2081 more items
  ]
}
[Info  - 6:36:02 PM] Connection to server got closed. Server will restart.
[Error - 6:36:02 PM] Request textDocument/semanticTokens/full failed.
Error: Connection got disposed.
	at Object.dispose (/nix/store/s3c7g5x3bgjl28nwjy9wdrzisqnbykf1-vscode-extension-chenglou92-rescript-vscode-1.3.0/share/vscode/extensions/chenglou92.rescript-vscode/client/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/nix/store/s3c7g5x3bgjl28nwjy9wdrzisqnbykf1-vscode-extension-chenglou92-rescript-vscode-1.3.0/share/vscode/extensions/chenglou92.rescript-vscode/client/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at LanguageClient.handleConnectionClosed (/nix/store/s3c7g5x3bgjl28nwjy9wdrzisqnbykf1-vscode-extension-chenglou92-rescript-vscode-1.3.0/share/vscode/extensions/chenglou92.rescript-vscode/client/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at LanguageClient.handleConnectionClosed (/nix/store/s3c7g5x3bgjl28nwjy9wdrzisqnbykf1-vscode-extension-chenglou92-rescript-vscode-1.3.0/share/vscode/extensions/chenglou92.rescript-vscode/client/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/nix/store/s3c7g5x3bgjl28nwjy9wdrzisqnbykf1-vscode-extension-chenglou92-rescript-vscode-1.3.0/share/vscode/extensions/chenglou92.rescript-vscode/client/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/nix/store/s3c7g5x3bgjl28nwjy9wdrzisqnbykf1-vscode-extension-chenglou92-rescript-vscode-1.3.0/share/vscode/extensions/chenglou92.rescript-vscode/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/nix/store/s3c7g5x3bgjl28nwjy9wdrzisqnbykf1-vscode-extension-chenglou92-rescript-vscode-1.3.0/share/vscode/extensions/chenglou92.rescript-vscode/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/nix/store/s3c7g5x3bgjl28nwjy9wdrzisqnbykf1-vscode-extension-chenglou92-rescript-vscode-1.3.0/share/vscode/extensions/chenglou92.rescript-vscode/client/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/nix/store/s3c7g5x3bgjl28nwjy9wdrzisqnbykf1-vscode-extension-chenglou92-rescript-vscode-1.3.0/share/vscode/extensions/chenglou92.rescript-vscode/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/nix/store/s3c7g5x3bgjl28nwjy9wdrzisqnbykf1-vscode-extension-chenglou92-rescript-vscode-1.3.0/share/vscode/extensions/chenglou92.rescript-vscode/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at IPCMessageReader.fireClose (/nix/store/s3c7g5x3bgjl28nwjy9wdrzisqnbykf1-vscode-extension-chenglou92-rescript-vscode-1.3.0/share/vscode/extensions/chenglou92.rescript-vscode/client/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
	at ChildProcess.<anonymous> (/nix/store/s3c7g5x3bgjl28nwjy9wdrzisqnbykf1-vscode-extension-chenglou92-rescript-vscode-1.3.0/share/vscode/extensions/chenglou92.rescript-vscode/client/node_modules/vscode-jsonrpc/lib/node/main.js:33:45)
	at ChildProcess.emit (node:events:402:35)
	at maybeClose (node:internal/child_process:1064:16)
	at Socket.<anonymous> (node:internal/child_process:450:11)
	at Socket.emit (node:events:390:28)
	at Pipe.<anonymous> (node:net:687:12)

... and 4 more times ...
```

I tried to execute the same command from bash. Indeed, it seems that `semanticTokesn` or `codeAction` do not exist for rescript-editor-analysis.exe.

Another query like `references` works:

```
> /home/jayesh/.vscode/extensions/chenglou92.rescript-vscode/server/analysis_binaries/linux/rescript-editor-analysis.exe documentSymbol /home/jayesh/project/src/SimulatedYield.res

[
{
        "name": "Risk",
        "kind": 2,
        "location": {"uri": "file:///home/jayesh/project/src/SimulatedYield.res", "range": {"start": {"line": 0, "character": 7}, "end": {"line": 41, "character": 1}}}
},
{
        "name": "t",
        "kind": 10,
        "location": {"uri": "file:///home/jayesh/project/src/SimulatedYield.res", "range": {"start": {"line": 1, "character": 2}, "end": {"line": 6, "character": 14}}}
},
... and so on ...
]
```

Is my distro (NixOS) giving me an outdated version of extension or rescript-editor-analysis.exe? I tried `-v` and `--version` on rescript-editor-analysis.exe to no avail.

Extension version is 1.3.0.

**Comment by jayesh-bhoot** [comment]
`Options` do not list `semanticTokens` and `codeAction` queries

```
$ /home/jayesh/.vscode/extensions/chenglou92.rescript-vscode/server/analysis_binaries/linux/rescript-editor-analysis.exe 

**Private CLI For rescript-vscode usage only**

API examples:
  ./rescript-editor-analysis.exe completion src/MyFile.res 0 4 currentContent.res
  ./rescript-editor-analysis.exe definition src/MyFile.res 9 3
  ./rescript-editor-analysis.exe typeDefinition src/MyFile.res 9 3
  ./rescript-editor-analysis.exe documentSymbol src/Foo.res
  ./rescript-editor-analysis.exe hover src/MyFile.res 10 2
  ./rescript-editor-analysis.exe references src/MyFile.res 10 2
  ./rescript-editor-analysis.exe rename src/MyFile.res 10 2 foo

Dev-time examples:
  ./rescript-editor-analysis.exe dump src/MyFile.res src/MyFile2.res
  ./rescript-editor-analysis.exe test src/MyFile.res

Note: positions are zero-indexed (start at 0 0), following LSP.
https://microsoft.github.io/language-server-protocol/specification#position

Options:
  completion: compute autocomplete for MyFile.res at line 0 and column 4,
    where MyFile.res is being edited and the editor content is in file current.res.

    ./rescript-editor-analysis.exe completion src/MyFile.res 0 4 current.res

  definition: get definition for item in MyFile.res at line 10 column 2:

    ./rescript-editor-analysis.exe definition src/MyFile.res 10 2

  typeDefinition: get type definition for item in MyFile.res at line 10 column 2:

    ./rescript-editor-analysis.exe typeDefinition src/MyFile.res 10 2

  documentSymbol: get all symbols declared in MyFile.res

    ./rescript-editor-analysis.exe documentSymbol src/MyFile.res

  hover: get inferred type for MyFile.res at line 10 column 2:

   ./rescript-editor-analysis.exe hover src/MyFile.res 10 2

  references: get all references to item in MyFile.res at line 10 column 2:

    ./rescript-editor-analysis.exe references src/MyFile.res 10 2

  rename: rename all appearances of item in MyFile.res at line 10 column 2 with foo:

    ./rescript-editor-analysis.exe rename src/MyFile.res 10 2 foo

  dump: for debugging, show all definitions and hovers for MyFile.res and MyFile.res:

    ./rescript-editor-analysis.exe dump src/Foo.res src/MyFile.res

  test: run tests specified by special comments in file src/MyFile.res

    ./rescript-editor-analysis.exe test src/src/MyFile.res
```

However, in my macbook, at least `semanticTokens` show up in options, and also works when executed:

```
$ /Users/jayesh/.vscode/extensions/chenglou92.rescript-vscode-1.3.0/server/analysis_binaries/darwin/rescript-editor-analysis.exe codeAction src/SimulatedYield.res 17 5

**Private CLI For rescript-vscode usage only**

API examples:
  ./rescript-editor-analysis.exe completion src/MyFile.res 0 4 currentContent.res
  ./rescript-editor-analysis.exe definition src/MyFile.res 9 3
  ./rescript-editor-analysis.exe typeDefinition src/MyFile.res 9 3
  ./rescript-editor-analysis.exe documentSymbol src/Foo.res
  ./rescript-editor-analysis.exe hover src/MyFile.res 10 2
  ./rescript-editor-analysis.exe references src/MyFile.res 10 2
  ./rescript-editor-analysis.exe rename src/MyFile.res 10 2 foo

Dev-time examples:
  ./rescript-editor-analysis.exe dump src/MyFile.res src/MyFile2.res
  ./rescript-editor-analysis.exe test src/MyFile.res

Note: positions are zero-indexed (start at 0 0), following LSP.
https://microsoft.github.io/language-server-protocol/specification#position

Options:

  completion: compute autocomplete for MyFile.res at line 0 and column 4,
    where MyFile.res is being edited and the editor content is in file current.res.

    ./rescript-editor-analysis.exe completion src/MyFile.res 0 4 current.res

  definition: get definition for item in MyFile.res at line 10 column 2:

    ./rescript-editor-analysis.exe definition src/MyFile.res 10 2

  typeDefinition: get type definition for item in MyFile.res at line 10 column 2:

    ./rescript-editor-analysis.exe typeDefinition src/MyFile.res 10 2

  documentSymbol: get all symbols declared in MyFile.res

    ./rescript-editor-analysis.exe documentSymbol src/MyFile.res

  hover: get inferred type for MyFile.res at line 10 column 2:

    ./rescript-editor-analysis.exe hover src/MyFile.res 10 2

  references: get all references to item in MyFile.res at line 10 column 2:

    ./rescript-editor-analysis.exe references src/MyFile.res 10 2

  rename: rename all appearances of item in MyFile.res at line 10 column 2 with foo:

    ./rescript-editor-analysis.exe rename src/MyFile.res 10 2 foo

  semanticTokens: return token semantic highlighting info for MyFile.res

    ./rescript-editor-analysis.exe semanticTokens src/MyFile.res

  createInterface: print to stdout the interface file for src/MyFile.res

    ./rescript-editor-analysis.exe createInterface src/MyFile.res lib/bs/src/MyFile.cmi

  format: print to stdout the formatted version of the provided file

    ./rescript-editor-analysis.exe format src/MyFile.res

  test: run tests specified by special comments in file src/MyFile.res

    ./rescript-editor-analysis.exe test src/src/MyFile.res
```

It indeed looks to be an issue of outdated version of rescript-editor-analysis.exe. Is there a way to verify this? 

But then, all of this still does not answer why `codeAction` was executed (and failed) in NixOS version of VS Code, but was not executed at all in Mac VS Code, given that this capability does not exist in either of the installations.

**Comment by zth** [comment]
@jayesh-bhoot this looks like a problem in the nix pkg configuration (or what it's called), and not with the extension itself, right?

**Comment by cristianoc** [comment]
In general, we are unable to debug nix specific things, and will need to rely on nix users to find out what the issues are and resolve them.

**Comment by zth** [comment]
Closing optimistically, please feel free to re-open @jayesh-bhoot if this is indeed something on our side.

**Comment by jayesh-bhoot** [comment]
Yep. Nothing here for you to resolve. Sorry I forgot to update this thread. I have already submitted a related PR to nixpkgs.
