### ISSUE TITLE
Server crash with TypeError: Cannot read properties of undefined (reading 'content')

### ISSUE THREAD

**Issue by Minnozz** [rescript-lang/rescript-vscode#548]
Extension version `v1.5.13`

Server crashes repeatedly:
```
TypeError: Cannot read properties of undefined (reading 'content')
    at Object.parseCompilerLogOutput (/nix/store/9kqvjbaq67qb6zwb2y8gvnr1y7m31mvl-vscode-extension-chenglou92-rescript-vscode-1.5.13/share/vscode/extensions/chenglou92.rescript-vscode/server/out/utils.js:531:61)
    at /nix/store/9kqvjbaq67qb6zwb2y8gvnr1y7m31mvl-vscode-extension-chenglou92-rescript-vscode-1.5.13/share/vscode/extensions/chenglou92.rescript-vscode/server/out/server.js:108:68
    at Map.forEach (<anonymous>)
    at sendUpdatedDiagnostics (/nix/store/9kqvjbaq67qb6zwb2y8gvnr1y7m31mvl-vscode-extension-chenglou92-rescript-vscode-1.5.13/share/vscode/extensions/chenglou92.rescript-vscode/server/out/server.js:105:19)
    at FSWatcher.<anonymous> (/nix/store/9kqvjbaq67qb6zwb2y8gvnr1y7m31mvl-vscode-extension-chenglou92-rescript-vscode-1.5.13/share/vscode/extensions/chenglou92.rescript-vscode/server/out/server.js:179:5)
    at FSWatcher.emit (node:events:390:28)
    at FSWatcher.emitWithAll (/nix/store/9kqvjbaq67qb6zwb2y8gvnr1y7m31mvl-vscode-extension-chenglou92-rescript-vscode-1.5.13/share/vscode/extensions/chenglou92.rescript-vscode/server/node_modules/chokidar/index.js:535:32)
    at FSWatcher._emit (/nix/store/9kqvjbaq67qb6zwb2y8gvnr1y7m31mvl-vscode-extension-chenglou92-rescript-vscode-1.5.13/share/vscode/extensions/chenglou92.rescript-vscode/server/node_modules/chokidar/index.js:626:8)
    at NodeFsHandler._handleFile (/nix/store/9kqvjbaq67qb6zwb2y8gvnr1y7m31mvl-vscode-extension-chenglou92-rescript-vscode-1.5.13/share/vscode/extensions/chenglou92.rescript-vscode/server/node_modules/chokidar/lib/nodefs-handler.js:400:14)
    at NodeFsHandler._addToNodeFs (/nix/store/9kqvjbaq67qb6zwb2y8gvnr1y7m31mvl-vscode-extension-chenglou92-rescript-vscode-1.5.13/share/vscode/extensions/chenglou92.rescript-vscode/server/node_modules/chokidar/lib/nodefs-handler.js:629:21)
[Info  - 3:59:15 PM] Connection to server got closed. Server will restart.
/nix/store/9kqvjbaq67qb6zwb2y8gvnr1y7m31mvl-vscode-extension-chenglou92-rescript-vscode-1.5.13/share/vscode/extensions/chenglou92.rescript-vscode/server/out/utils.js:531
            parsedDiagnostics[parsedDiagnostics.length - 1].content.push(line);
                                                            ^
```

**Comment by zth** [comment]
Will tackle this soon.
