### ISSUE TITLE
Error: A request has failed occurs whenever there's a white space in the project path.

### ISSUE THREAD

**Issue by shrihari689** [rescript-lang/rescript-vscode#78]
#### `src/practice.res`
```
Js.log("Hello World")
```
#### `/bsconfig.json`
```
{
  "name": "learn-rescript",
  "version": "0.0.1",
  "sources": {
    "dir": "src",
    "subdirs": true
  },
  "package-specs": {
    "module": "commonjs",
    "in-source": true
  },
  "suffix": ".bs.js",
  "bs-dependencies": [],
  "warnings": {
    "error": "+101"
  },
  "reason": {
    "react-jsx": 3
  }
}
```

#### `/package.json`
```
{
  "name": "learn-rescript",
  "version": "0.0.1",
  "description": "ReScript language",
  "scripts": {
    "build": "bsb -make-world",
    "clean": "bsb -clean-world",
    "start": "bsb -make-world -w"
  },
  "keywords": [
    "rescript"
  ],
  "devDependencies": {
    "bs-platform": "^8.4.2"
  },
  "dependencies": {
    "bs-platform": "^8.4.2"
  }
}
```

#### `Error Logs on Output Tab VS Code`

```
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at c:\Users\SHRI HARI\.vscode\extensions\chenglou92.rescript-vscode-1.0.5\server\out\RescriptEditorSupport.js:57:31
    at ChildProcess.exithandler (child_process.js:319:5)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
[Info  - 3:09:10 pm] Connection to server got closed. Server will restart.
[Error - 3:09:10 pm] Request textDocument/hover failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\SHRI HARI\.vscode\extensions\chenglou92.rescript-vscode-1.0.5\client\node_modules\vscode-jsonrpc\lib\main.js:904:25)
    at Object.dispose (c:\Users\SHRI HARI\.vscode\extensions\chenglou92.rescript-vscode-1.0.5\client\node_modules\vscode-languageclient\lib\client.js:74:35)
    at LanguageClient.handleConnectionClosed (c:\Users\SHRI HARI\.vscode\extensions\chenglou92.rescript-vscode-1.0.5\client\node_modules\vscode-languageclient\lib\client.js:2309:42)
    at LanguageClient.handleConnectionClosed (c:\Users\SHRI HARI\.vscode\extensions\chenglou92.rescript-vscode-1.0.5\client\node_modules\vscode-languageclient\lib\main.js:155:15)
    at closeHandler (c:\Users\SHRI HARI\.vscode\extensions\chenglou92.rescript-vscode-1.0.5\client\node_modules\vscode-languageclient\lib\client.js:2296:18)
    at CallbackList.invoke (c:\Users\SHRI HARI\.vscode\extensions\chenglou92.rescript-vscode-1.0.5\client\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (c:\Users\SHRI HARI\.vscode\extensions\chenglou92.rescript-vscode-1.0.5\client\node_modules\vscode-jsonrpc\lib\events.js:121:36)
    at closeHandler (c:\Users\SHRI HARI\.vscode\extensions\chenglou92.rescript-vscode-1.0.5\client\node_modules\vscode-jsonrpc\lib\main.js:240:26)
    at CallbackList.invoke (c:\Users\SHRI HARI\.vscode\extensions\chenglou92.rescript-vscode-1.0.5\client\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (c:\Users\SHRI HARI\.vscode\extensions\chenglou92.rescript-vscode-1.0.5\client\node_modules\vscode-jsonrpc\lib\events.js:121:36)
    at IPCMessageReader.fireClose (c:\Users\SHRI HARI\.vscode\extensions\chenglou92.rescript-vscode-1.0.5\client\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
    at ChildProcess.<anonymous> (c:\Users\SHRI HARI\.vscode\extensions\chenglou92.rescript-vscode-1.0.5\client\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
    at ChildProcess.emit (events.js:327:22)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

#### `/lib/bs/.compiler.log`
```
#Start(592075014)
#Done(592075527)
```

#### Screenshot

![image](https://user-images.githubusercontent.com/57325503/107015554-df251d80-67c2-11eb-9611-44f31739ead6.png)

**Comment by cristianoc** [comment]
@shrihari689 to help debug, would you go to the directory where `bsconfig.json` is and do:
```
c:\Users\SHRI HARI\.vscode\extensions\chenglou92.rescript-vscode-1.0.5\server\win32/rescript-editor-support.exe dump practice.res >out.json
```
Then see what json file is produced.

**Comment by shrihari689** [comment]
This is what the command produced.

#### `out.json`

```
[
    {
        "range": {
            "start": {
                "line": 0,
                "character": 7
            },
            "end": {
                "line": 0,
                "character": 21
            }
        },
        "hover": "string"
    },
    {
        "range": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 0,
                "character": 2
            }
        },
        "hover": "```rescript\nmodule Js = {\n  type rec t<+'a>\n  module Fn\n  module MapperRt\n  module Internal\n  type rec null<+'a>\n  type rec undefined<+'a>\n  type rec nullable<+'a>\n  type rec null_undefined<'a> = nullable<'a>\n  let toOption: nullable<'a> => option<'a>\n  let undefinedToOption: undefined<'a> => option<'a>\n  let nullToOption: null<'a> => option<'a>\n  let isNullable: nullable<'a> => bool\n  let testAny: 'a => bool\n  type rec promise<+'a, +'e>\n  let null: null<'a>\n  let undefined: undefined<'a>\n  let typeof: 'a => string\n  let log: 'a => unit\n  let log2: ('a, 'b) => unit\n  let log3: ('a, 'b, 'c) => unit\n  let log4: ('a, 'b, 'c, 'd) => unit\n  let logMany: array<'a> => unit\n  let eqNull: ('a, null<'a>) => bool\n  let eqUndefined: ('a, undefined<'a>) => bool\n  let eqNullable: ('a, nullable<'a>) => bool\n  let unsafe_lt: ('a, 'a) => bool\n  let unsafe_le: ('a, 'a) => bool\n  let unsafe_gt: ('a, 'a) => bool\n  let unsafe_ge: ('a, 'a) => bool\n  module Null\n  module Undefined\n  module Nullable\n  module Null_undefined\n  module Exn\n  module Array\n  module Array2\n  module String\n  module String2\n  module Re\n  module Promise\n  module Date\n  module Dict\n  module Global\n  module Json\n  module Math\n  module Obj\n  module Typed_array\n  module TypedArray2\n  module Types\n  module Float\n  module Int\n  module Option\n  module Result\n  module List\n  module Vector\n  module Console\n}\n```",
        "definition": {
            "uri": "file://e:/ReScript/rescript-tutorial/node_modules/bs-platform/lib/ocaml/js.ml",
            "range": {
                "start": {
                    "line": 0,
                    "character": 0
                },
                "end": {
                    "line": 0,
                    "character": 0
                }
            }
        }
    },
    {
        "range": {
            "start": {
                "line": 0,
                "character": 3
            },
            "end": {
                "line": 0,
                "character": 6
            }
        },
        "hover": "```rescript\n'a => unit\n```\n\nA convenience function to log everything\n\n\n\nfile://e:/ReScript/rescript-tutorial/node_modules/bs-platform/lib/ocaml/js.ml",
        "definition": {
            "uri": "file://e:/ReScript/rescript-tutorial/node_modules/bs-platform/lib/ocaml/js.ml",
            "range": {
                "start": {
                    "line": 187,
                    "character": 9
                },
                "end": {
                    "line": 187,
                    "character": 12
                }
            }
        }
    }
]
```

#### `src/practice.res`
![image](https://user-images.githubusercontent.com/57325503/107041893-0ee61c80-67e7-11eb-865c-762b78642fe1.png)

#### When Opening the File
![image](https://user-images.githubusercontent.com/57325503/107042066-4f459a80-67e7-11eb-9e51-c6f7166310f4.png)

#### In Output Tab on VSCode

```
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at c:\Users\SHRI HARI\.vscode\extensions\chenglou92.rescript-vscode-1.0.5\server\out\RescriptEditorSupport.js:57:31
    at ChildProcess.exithandler (child_process.js:319:5)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
[Error - 7:16:53 pm] Connection to server got closed. Server will not be restarted.
[Error - 7:16:53 pm] Request textDocument/hover failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\SHRI HARI\.vscode\extensions\chenglou92.rescript-vscode-1.0.5\client\node_modules\vscode-jsonrpc\lib\main.js:904:25)
    at Object.dispose (c:\Users\SHRI HARI\.vscode\extensions\chenglou92.rescript-vscode-1.0.5\client\node_modules\vscode-languageclient\lib\client.js:74:35)
    at LanguageClient.handleConnectionClosed (c:\Users\SHRI HARI\.vscode\extensions\chenglou92.rescript-vscode-1.0.5\client\node_modules\vscode-languageclient\lib\client.js:2309:42)
    at LanguageClient.handleConnectionClosed (c:\Users\SHRI HARI\.vscode\extensions\chenglou92.rescript-vscode-1.0.5\client\node_modules\vscode-languageclient\lib\main.js:155:15)
    at closeHandler (c:\Users\SHRI HARI\.vscode\extensions\chenglou92.rescript-vscode-1.0.5\client\node_modules\vscode-languageclient\lib\client.js:2296:18)
    at CallbackList.invoke (c:\Users\SHRI HARI\.vscode\extensions\chenglou92.rescript-vscode-1.0.5\client\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (c:\Users\SHRI HARI\.vscode\extensions\chenglou92.rescript-vscode-1.0.5\client\node_modules\vscode-jsonrpc\lib\events.js:121:36)
    at closeHandler (c:\Users\SHRI HARI\.vscode\extensions\chenglou92.rescript-vscode-1.0.5\client\node_modules\vscode-jsonrpc\lib\main.js:240:26)
    at CallbackList.invoke (c:\Users\SHRI HARI\.vscode\extensions\chenglou92.rescript-vscode-1.0.5\client\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (c:\Users\SHRI HARI\.vscode\extensions\chenglou92.rescript-vscode-1.0.5\client\node_modules\vscode-jsonrpc\lib\events.js:121:36)
    at IPCMessageReader.fireClose (c:\Users\SHRI HARI\.vscode\extensions\chenglou92.rescript-vscode-1.0.5\client\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
    at ChildProcess.<anonymous> (c:\Users\SHRI HARI\.vscode\extensions\chenglou92.rescript-vscode-1.0.5\client\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
    at ChildProcess.emit (events.js:327:22)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

```

**Comment by cristianoc** [comment]
@shrihari689 thanks -- looks like the json produced is well-formed. Which does not explain what's going on when opening the `.res` file in the editor. Presumably the specific call to `rescript-editor-support.exe` in that situation behaves differently.

Wondering whether an even simpler example still shows the same issues.

**Comment by shrihari689** [comment]
I gone through the Source Code for hours and fixed it by a workaround.
On Line [37](https://github.com/rescript-lang/rescript-vscode/blob/master/server/src/RescriptEditorSupport.ts#L37) and [68](https://github.com/rescript-lang/rescript-vscode/blob/master/server/src/RescriptEditorSupport.ts#L68), we are concatenating the strings.
But it my scenario, my username in my system was `SHRI HARI` (space), so the command fails 😶

![Uploading image.png…]()


So I fixed by this way and it is now working on my machine.

**Comment by cristianoc** [comment]
@shrihari689 well spotted, thanks a lot for digging in and figure out the issue!
