### ISSUE TITLE
server is not a function

### ISSUE THREAD

**Issue by DZakh** [rescript-lang/rescript-vscode#871]
```
/Users/dzakh/.vscode/extensions/chenglou92.rescript-vscode-1.29.10/server/out/cli.js:20
            return server(false);
                   ^

TypeError: server is not a function
    at /Users/dzakh/.vscode/extensions/chenglou92.rescript-vscode-1.29.10/server/out/cli.js:20:20
    at Object.<anonymous> (/Users/dzakh/.vscode/extensions/chenglou92.rescript-vscode-1.29.10/server/out/cli.js:33:3)
    at Module._compile (node:internal/modules/cjs/loader:1316:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
    at Module.load (node:internal/modules/cjs/loader:1171:32)
    at Module._load (node:internal/modules/cjs/loader:1012:12)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:96:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.15.0
[Error - 6:26:45 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 6:26:45 PM] Connection to server got closed. Server will restart.
true
[Error - 6:26:45 PM] ReScript Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
/Users/dzakh/.vscode/extensions/chenglou92.rescript-vscode-1.29.10/server/out/cli.js:20
            return server(false);
```
I'll try to reproduce, but there's nothing special in the project

**Comment by zth** [comment]
Seems this recent commit broke it: https://github.com/rescript-lang/rescript-vscode/commit/e54c067fdadd59c81dfe7660ee5f295c610345f6

Wish that was something tests could catch. Anyway, @aspeddro looks like we need another solution for the version stuff.

**Comment by DZakh** [comment]
Works after revert.

> Wish that was something tests could catch

Probably a single e2e test spawning the process like here https://github.com/rescript-lang/rescript-compiler/blob/master/jscomp/build_tests/cli_help/input.js would prevent it.
